### ISSUE TITLE
Not sure TLM works with Blender 3.0

### ISSUE THREAD

**Issue by kitaedesigns** [Naxela/The_Lightmapper#143]
This Error message appears when Building Lightmaps

"
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thelightmapper\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thelightmapper\addon\utility\build.py", line 91, in prepare_build
    prepare.init(self, previous_settings)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thelightmapper\addon\utility\cycles\prepare.py", line 18, in init
    set_settings()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thelightmapper\addon\utility\cycles\prepare.py", line 590, in set_settings
    scene.render.tile_x = 256
AttributeError: 'RenderSettings' object has no attribute 'tile_x'

location: <unknown location>:-1
"

**Comment by Naxela** [comment]
Hi, and thanks for reporting this bug!

I added a new release where I think this should be solved: https://github.com/Naxela/The_Lightmapper/releases/tag/0.6.12 

Let me know if the problem still occurs

**Comment by kitaedesigns** [comment]
With the latest build I get this error when trying to install the plugin.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'The_Lightmapper-0'

**Comment by Naxela** [comment]
Hi, I just updated the binaries in the build (https://github.com/Naxela/The_Lightmapper/releases/tag/0.6.12) so that the name error shouldn't occur - Are you using Blender 3.0 or Blender 3.1?

**Comment by kitaedesigns** [comment]
Currently using Blender 3.0. I will try the latest release again and see if maybe I'm doing something wrong but I have tried using the provided zip, also unzipping and zipping the addon folder within the plugin and it doesn't seem to be working.

**Comment by kitaedesigns** [comment]
No mine has the specific lightmapper version in the file path.
![image](https://user-images.githubusercontent.com/23407511/154982149-e7523b8e-5283-456b-8103-42a9c6d5d832.png)

**Comment by Naxela** [comment]
I think that could be the reason. If you rename it to thelightmapper (with lowercase), does it still not work?

**Comment by kitaedesigns** [comment]
that seemed to do the trick! thanks!

**Comment by Naxela** [comment]
Usually I name the folder like that in the zip, but I think that in the previous zipped file I might have forgotten, which caused the error - Good to hear it's resolved!

**Comment by kitaedesigns** [comment]
Yes it seems to be working fine although is it normal for there to be .pfm files generated now? Not sure what these are. I was trying to use SDR Encoding to produce .png lightmaps but then these appeared. 

![image](https://user-images.githubusercontent.com/23407511/155254541-3d5e0452-8bdb-4dbf-9af5-358fa5f7284d.png)

**Comment by Naxela** [comment]
Hi, the .pfm files are completely normal. They are required by the Intel denoising (since it doens't support .hdr or .exr files). I'll add a cleaning function one of these days, but so far it's safe to delete those.

**Comment by kitaedesigns** [comment]
There seems to be a problem with the SDR Encoding option that gets confused with directories since so many files are being produced and the lightmap paths aren't correct resulting in missing textures in the shader graph
![image](https://user-images.githubusercontent.com/23407511/155462191-37010d73-a0d0-4ea8-aa15-e40bdab96b8b.png)
![image](https://user-images.githubusercontent.com/23407511/155462214-c228b3e5-0306-4fac-87bb-3adb4edabd55.png)

**Comment by kitaedesigns** [comment]
Seems to be some sort of problem with packed images in temporary memory.
![image](https://user-images.githubusercontent.com/23407511/156290616-e7bcdc39-0c0a-45d9-9f0f-fc5f4be1ee3b.png)

**Comment by Naxela** [comment]
That seems strange, so it seems to be caused by the combination of SDR encoding and packed images? - If you make a copy of the blend file and unpack the textures locally, does it work in that case?

**Comment by kitaedesigns** [comment]
Copying the project and unpacking doesn't seem to work. I think the problem is that the name of the texture being referenced in the shader does not match any of the texture names when Encoding with RGBD is enabled since the texture created in the shader is named "meshname__baked" it doesn't know which extension to use so it ends up being a missing reference. 
![image](https://user-images.githubusercontent.com/23407511/157307872-86724e99-c771-4824-a1df-9238bd0edecb.png)
